FROM sprungknoedl/dagobert:latest
USER root
ADD https://github.com/Yamato-Security/hayabusa/releases/download/v3.2.0/hayabusa-3.2.0-lin-x64-musl.zip /usr/src/hayabusa-3.2.0-lin-x64-musl.zip

RUN apt update && apt install -y ca-certificates unzip
RUN unzip /usr/src/hayabusa-3.2.0-lin-x64-musl.zip -d /home/sprungknoedl
RUN mv hayabusa-3.2.0-lin-x64-musl hayabusa && chmod +x hayabusa
RUN mkdir -p /home/sprungknoedl/files && chown -R sprungknoedl:users /home/sprungknoedl

USER sprungknoedl
RUN ./hayabusa update-rules
ENV MODULE_HAYABUSA=/home/sprungknoedl/hayabusa
CMD [ "/home/sprungknoedl/dagobert", "worker" ]