volumes:
  data:

services:
  app:
    image: sprungknoedl/dagobert-full
    restart: unless-stopped
    volumes:
      - data:/home/plaso/files
    env_file: dagobert.env
    ports:
      - 8080:8080
