CREATE TABLE IF NOT EXISTS custom_attributes (
	id      TEXT NOT NULL PRIMARY KEY,
	entity  TEXT NOT NULL DEFAULT '',
	label   TEXT NOT NULL DEFAULT '',
	type    TEXT NOT NULL DEFAULT '',
	options TEXT NOT NULL DEFAULT '',
	rank    INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE cases ADD COLUMN custom TEXT NOT NULL DEFAULT '';
ALTER TABLE assets ADD COLUMN custom TEXT NOT NULL DEFAULT '';
ALTER TABLE events ADD COLUMN custom TEXT NOT NULL DEFAULT '';
ALTER TABLE evidences ADD COLUMN custom TEXT NOT NULL DEFAULT '';
ALTER TABLE indicators ADD COLUMN custom TEXT NOT NULL DEFAULT '';
ALTER TABLE malware ADD COLUMN custom TEXT NOT NULL DEFAULT '';
ALTER TABLE notes ADD COLUMN custom TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN custom TEXT NOT NULL DEFAULT '';
