version: '3'

volumes:
  data:

services:
  app:
    image: sprungknoedl/dagobert:main
    restart: unless-stopped
    volumes:
      - data:/app/files/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "OIDC_CLIENT_ID=<<<CLIENT_ID>>>"
      - "OIDC_CLIENT_SECRET=<<<CLIENT_SECRET>>>"
      - "OIDC_CLIENT_URL=https://<<<CLIENT_URL>>>/auth/callback"
      - "OIDC_ISSUER=https://login.microsoftonline.com/<<<AZURE_TENANT>>>/v2.0"
      - "OIDC_ID_CLAIM=oid"
      - "WEB_SESSION_SECRET=<<<RANDOM_VALUE>>>"
      - "DAGOBERT_ADMIN=<<<ADMIN_USER_ID>>>"
      - "DOCKER_MOUNT=/var/lib/docker/volumes/dagobert_data/_data"
