// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlite

import (
	"database/sql"

	ulid "github.com/oklog/ulid/v2"
)

type Asset struct {
	ID           ulid.ULID
	CaseID       ulid.ULID
	Type         sql.NullString
	Name         sql.NullString
	Ip           sql.NullString
	Description  sql.NullString
	Compromised  sql.NullString
	Analysed     sql.NullFloat64
	DateAdded    sql.NullTime
	DateModified sql.NullTime
	UserAdded    sql.NullString
	UserModified sql.NullString
}

type Case struct {
	ID             ulid.ULID
	Name           string
	Closed         sql.NullFloat64
	Classification sql.NullString
	Severity       string
	Outcome        sql.NullString
	Summary        sql.NullString
	DateAdded      sql.NullTime
	DateModified   sql.NullTime
	UserAdded      sql.NullString
	UserModified   sql.NullString
}

type Event struct {
	ID           ulid.ULID
	CaseID       ulid.ULID
	Time         sql.NullTime
	Type         sql.NullString
	AssetA       sql.NullString
	AssetB       sql.NullString
	Direction    sql.NullString
	Event        sql.NullString
	Raw          sql.NullString
	KeyEvent     sql.NullFloat64
	DateAdded    sql.NullTime
	DateModified sql.NullTime
	UserAdded    sql.NullString
	UserModified sql.NullString
}
